/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// InlineObject struct for InlineObject
type InlineObject struct {
	// 吊起小程序时的参数
	MicroAppUrl string `json:"micro_app_url,omitempty"`
	// 地理位置id
	PoiId string `json:"poi_id,omitempty"`
	// 地理位置名称
	PoiName string `json:"poi_name,omitempty"`
	// 标题，可以带话题。 如title1#话题1
	Text string `json:"text,omitempty"`
	// 通过/image/upload/接口得到
	ImageId string `json:"image_id,omitempty"`
	// 小程序id
	MicroAppId string `json:"micro_app_id,omitempty"`
	// 小程序标题
	MicroAppTitle string `json:"micro_app_title,omitempty"`
	// 如果需要at其他用户。将text中@nickname对应的open_id放到这里。
	AtUsers []string `json:"at_users,omitempty"`
}
