/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// VideoCommentReplyRsp
type VideoCommentReplyRsp struct {
	Data  DouyinVideoPartUploadRspData `json:"data,omitempty"`
	Extra ConnectRspExtra              `json:"extra,omitempty"`
}
