/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// InlineObject20 struct for InlineObject20
type InlineObject20 struct {
	// 角色名（暂未开放）
	RoleName string `json:"role_name,omitempty"`
	// 昵称
	Nickname string `json:"nickname,omitempty"`
}
