/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// PoiSupplierAttributes1104Breakfast 早餐政策
type PoiSupplierAttributes1104Breakfast struct {
	Price int64 `json:"price,omitempty"`
	Type  int64 `json:"type,omitempty"`
}
