/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// PoiOrderSyncReqExtShopInfo struct for PoiOrderSyncReqExtShopInfo
type PoiOrderSyncReqExtShopInfo struct {
	// 外部商户ID
	ExtShopId string `json:"ext_shop_id,omitempty"`
	// 抖音商户ID
	ShopId string `json:"shop_id,omitempty"`
}
