/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// FollowingListRsp
type FollowingListRsp struct {
	Data FollowingListRspData `json:"data,omitempty"`
}
