/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// AccessTokenRspData struct for AccessTokenRspData
type AccessTokenRspData struct {
	// 接口调用凭证
	AccessToken string `json:"access_token,omitempty"`
	// 错误码描述
	Description string `json:"description,omitempty"`
	// 错误码
	ErrorCode int64 `json:"error_code,omitempty"`
	// access_token接口调用凭证超时时间，单位（秒
	ExpiresIn int64 `json:"expires_in,omitempty"`
	// 授权用户唯一标识
	OpenId string `json:"open_id,omitempty"`
	// 用户刷新access_token
	RefreshToken string `json:"refresh_token,omitempty"`
	// 用户授权的作用域(Scope)，使用逗号（,）分隔，开放平台几乎几乎每个接口都需要特定的Scope。
	Scope string `json:"scope,omitempty"`
	// 当且仅当该网站应用已获得该用户的userinfo授权时，才会出现该字段。
	Unionid string `json:"unionid,omitempty"`
}
