/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package https://github.com/xopenapi/douyin-open-api-go/douyin
// ApiResponseExtra struct for ApiResponseExtra
type ApiResponseExtra struct {
	Logid string `json:"logid,omitempty"`
	Now int64 `json:"now,omitempty"`
}
