/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// EnterpriseImPersonListRspDataPersonas struct for EnterpriseImPersonListRspDataPersonas
type EnterpriseImPersonListRspDataPersonas struct {
	Nickname  string `json:"nickname,omitempty"`
	PersonaId string `json:"persona_id,omitempty"`
	RoleName  string `json:"role_name,omitempty"`
}
