/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// InlineObject31 struct for InlineObject31
type InlineObject31 struct {
	// 订单支付状态。0 - 未支付, 1 - 已支付
	Status int64 `json:"status,omitempty"`
	// 入住时间 yyyyMMdd
	CheckIn string `json:"check_in,omitempty"`
	// 离店时间 yyyyMMdd
	CheckOut string `json:"check_out,omitempty"`
	// 预订人姓名
	CustomerName string `json:"customer_name,omitempty"`
	// 预订人电话
	CustomerPhone int64 `json:"customer_phone,omitempty"`
	// 抖音订单号
	OrderId string `json:"order_id,omitempty"`
	// 备注
	Remark string `json:"remark,omitempty"`
	// 总价, 单位人民币分
	TotalPrice int64 `json:"total_price,omitempty"`
	// 预定数量
	ReserveAmount int64 `json:"reserve_amount,omitempty"`
	// 接入方房型ID
	SpuExtId     string                               `json:"spu_ext_id,omitempty"`
	DatePrice    []PoiExtHotelOrderCommitDatePrice    `json:"date_price,omitempty"`
	CustomerList []PoiExtHotelOrderCommitCustomerList `json:"customer_list,omitempty"`
}
