/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// InlineObject25 struct for InlineObject25
type InlineObject25 struct {
	// 团购活动Id
	GrouponId string `json:"groupon_id,omitempty"`
}
