/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// DouyinPayOrderQueryRsp
type DouyinPayOrderQueryRsp struct {
	Data  DouyinPayOrderQueryRspData `json:"data,omitempty"`
	Extra FansDataRspExtra           `json:"extra,omitempty"`
}
