/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// DouyinVideoCreateReq
type DouyinVideoCreateReq struct {
	// 文章ID，暂不开放
	ArticleId string `json:"article_id,omitempty"`
	// 视频标题， 可以带话题,@用户。 如title1#话题1
	Text string `json:"text,omitempty"`
	// 时效新闻标签，1表示使用。暂不开放
	TimelinessLabel int64 `json:"timeliness_label,omitempty"`
	// 文章自定义标题，暂不开放
	ArticleTitle string `json:"article_title,omitempty"`
	// 将传入的指定时间点对应帧设置为视频封面（单位：秒）
	CoverTsp float32 `json:"cover_tsp,omitempty"`
	// 小程序标题
	MicroAppTitle string `json:"micro_app_title,omitempty"`
	// video_id, 通过/video/upload/接口得到。注意每次调用/video/create/都要调用/video/upload/生成新的video_id
	VideoId string `json:"video_id,omitempty"`
	// 游戏id。暂不开放
	GameId string `json:"game_id,omitempty"`
	// 小程序id
	MicroAppId string `json:"micro_app_id,omitempty"`
	// 地理位置id
	PoiId string `json:"poi_id,omitempty"`
	// 游戏个性化参数
	GameContent string `json:"game_content,omitempty"`
	// 地理位置名称
	PoiName string `json:"poi_name,omitempty"`
	// 最多可添加3个，用`\\|`隔开。暂不开放
	TimelinessKeyword string `json:"timeliness_keyword,omitempty"`
	// 如果需要at其他用户。将text中@nickname对应的open_id放到这里。
	AtUsers []string `json:"at_users,omitempty"`
}
