/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// InlineObject35 struct for InlineObject35
type InlineObject35 struct {
	Media []string `json:"media,omitempty"`
}
