/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// PoiSupplierMatchQueryRsp
type PoiSupplierMatchQueryRsp struct {
	Data  PoiSupplierMatchRspData `json:"data,omitempty"`
	Extra FansDataRspExtra        `json:"extra,omitempty"`
}
