/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// PoiSupplierQueryRspDataSyncStatus struct for PoiSupplierQueryRspDataSyncStatus
type PoiSupplierQueryRspDataSyncStatus struct {
	FailReason     string `json:"fail_reason,omitempty"`
	LastSyncStatus string `json:"last_sync_status,omitempty"`
}
