/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// DiscoveryEntRankItemRsp
type DiscoveryEntRankItemRsp struct {
	Data  DiscoveryEntRankItemRspData `json:"data,omitempty"`
	Extra FansDataRspExtra            `json:"extra,omitempty"`
}
