/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// DataExternalPoiClaimListRspData struct for DataExternalPoiClaimListRspData
type DataExternalPoiClaimListRspData struct {
	// 错误描述
	Description string `json:"description,omitempty"`
	// 返回错误码
	ErrorCode int64 `json:"error_code,omitempty"`
	// 错误描述
	HasMore bool `json:"has_more,omitempty"`
	// 总量
	Total int64 `json:"total,omitempty"`
	// 用于下一页请求的cursor
	Cursor int64                                 `json:"cursor,omitempty"`
	List   []DataExternalPoiClaimListRspDataList `json:"list,omitempty"`
}
