/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// EnterpriseImPersonDeleteReq
type EnterpriseImPersonDeleteReq struct {
	// 客服id
	PersonaId string `json:"persona_id,omitempty"`
}
