/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// EnterpriseGrouponSaveRspData struct for EnterpriseGrouponSaveRspData
type EnterpriseGrouponSaveRspData struct {
	// 错误码
	ErrorCode int64 `json:"error_code,omitempty"`
	// 错误码描述
	Description string `json:"description,omitempty"`
	// 团购活动Id，审核失败修改用
	GrouponId string `json:"groupon_id,omitempty"`
}
