/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// PoiSupplierEntry struct for PoiSupplierEntry
type PoiSupplierEntry struct {
	// 入口类型(1:H5，2:抖音小程序)
	EntryType    int64                        `json:"entry_type,omitempty"`
	EntryMiniApp PoiSupplierEntryEntryMiniApp `json:"entry_mini_app,omitempty"`
}
