/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// AuthorizeRsp
type AuthorizeRsp struct {
	Data  ConnectRspData  `json:"data,omitempty"`
	Extra ConnectRspExtra `json:"extra,omitempty"`
}
