/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// PoiSupplierAttributes3101 下单模板。1 - 国内模板, 2 - 海外模板
type PoiSupplierAttributes3101 struct {
	// 优待政策(不超过200个汉字)
	PreferentialPolicy    []PoiSupplierAttributes3101PreferentialPolicy  `json:"preferential_policy,omitempty"`
	PreferentialPolicyExt PoiSupplierAttributes3101PreferentialPolicyExt `json:"preferential_policy_ext,omitempty"`
	// 景点介绍(不超过2000个汉字)
	ScenicIntro []PoiSupplierAttributes3101ScenicIntro `json:"scenic_intro,omitempty"`
	// 交通(不超过200个汉字)
	Traffic []PoiSupplierAttributes3101ScenicIntro `json:"traffic,omitempty"`
	// 服务设施列表
	Facility []PoiSupplierAttributes3101Facility `json:"facility,omitempty"`
	// 宠物携带(1:可携带宠物，2:不可携带宠物)
	Pet int32 `json:"pet,omitempty"`
	// 开放时间
	OpenTime string `json:"open_time,omitempty"`
	// 玩法介绍(不超过200个汉字)
	PlayIntro []PoiSupplierAttributes3101ScenicIntro `json:"play_intro,omitempty"`
	// 玩法介绍(不超过200个汉字)
	OpenTimeExt []PoiSupplierAttributes3101ScenicIntro `json:"open_time_ext,omitempty"`
}
