/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// VideoCommentListRsp
type VideoCommentListRsp struct {
	Data VideoCommentListRspData `json:"data,omitempty"`
}
