/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// EnterpriseImCardListRspDataCards struct for EnterpriseImCardListRspDataCards
type EnterpriseImCardListRspDataCards struct {
	CardId       string `json:"card_id,omitempty"`
	CardType     string `json:"card_type,omitempty"`
	Content      string `json:"content,omitempty"`
	RejectReason string `json:"reject_reason,omitempty"`
	Status       string `json:"status,omitempty"`
}
