/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// EnterpriseImCardDeleteReq
type EnterpriseImCardDeleteReq struct {
	CardId string `json:"card_id,omitempty"`
}
