/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// DouyinImageUploadRspDataImage struct for DouyinImageUploadRspDataImage
type DouyinImageUploadRspDataImage struct {
	Height  int64  `json:"height,omitempty"`
	ImageId string `json:"image_id,omitempty"`
	Width   int64  `json:"width,omitempty"`
}
