/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// TouTiaoVideoPartCompleteRspDataVideo struct for TouTiaoVideoPartCompleteRspDataVideo
type TouTiaoVideoPartCompleteRspDataVideo struct {
	Height int64 `json:"height,omitempty"`
	// 视频文件id
	VideoId int64 `json:"video_id,omitempty"`
	Width   int64 `json:"width,omitempty"`
}
