/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// InlineObject5 struct for InlineObject5
type InlineObject5 struct {
	Video []string `json:"video,omitempty"`
}
