/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// InlineObject34 struct for InlineObject34
type InlineObject34 struct {
	// 外部平台SPU ID
	SpuExtId string           `json:"spu_ext_id,omitempty"`
	Skus     []PoiSkuSyncSkus `json:"skus,omitempty"`
}
