/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// StarAuthorScoreV2RspData struct for StarAuthorScoreV2RspData
type StarAuthorScoreV2RspData struct {
	// 错误码
	ErrorCode int64 `json:"error_code,omitempty"`
	// 错误码描述
	Description string `json:"description,omitempty"`
	// 合作指数
	CooperationScore float32 `json:"cooperation_score,omitempty"`
	// 性价比指数
	CpScore float32 `json:"cp_score,omitempty"`
	// 性价比指数
	GrowthScore float32 `json:"growth_score,omitempty"`
	NickName    string  `json:"nick_name,omitempty"`
	// 种草指数
	ShopScore float32 `json:"shop_score,omitempty"`
	// 传播指数
	SpreadScore float32 `json:"spread_score,omitempty"`
	// 星图指数
	StarScore float32 `json:"star_score,omitempty"`
	// 达人抖音号
	UniqueId string `json:"unique_id,omitempty"`
	// 达人指数更新时间戳
	UpdateTimestamp int64 `json:"update_timestamp,omitempty"`
}
