/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// DataExternalUserProfileRspData struct for DataExternalUserProfileRspData
type DataExternalUserProfileRspData struct {
	// 错误码
	ErrorCode int64 `json:"error_code,omitempty"`
	// 错误码描述
	Description string                                     `json:"description,omitempty"`
	ResultList  []DataExternalUserProfileRspDataResultList `json:"result_list,omitempty"`
}
