/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// InlineObject17 struct for InlineObject17
type InlineObject17 struct {
	// 是否绑定
	Bind bool `json:"bind,omitempty"`
	// 标签id
	TagId int64 `json:"tag_id,omitempty"`
	// 用户openid
	UserId string `json:"user_id,omitempty"`
}
