/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// User
type User struct {
	Avatar   string `json:"avatar,omitempty"`
	City     string `json:"city,omitempty"`
	Country  string `json:"country,omitempty"`
	Gender   int64  `json:"gender,omitempty"`
	Nickname string `json:"nickname,omitempty"`
	OpenId   string `json:"open_id,omitempty"`
	Province string `json:"province,omitempty"`
	UnionId  string `json:"union_id,omitempty"`
}
