/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// DouyinPayAccountTransRsp
type DouyinPayAccountTransRsp struct {
	Data  DouyinPayAccountTransRspData `json:"data,omitempty"`
	Extra FansDataRspExtra             `json:"extra,omitempty"`
}
