/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// EnterpriseLeadsUserActionListRspDataList struct for EnterpriseLeadsUserActionListRspDataList
type EnterpriseLeadsUserActionListRspDataList struct {
	ActionFlag   string `json:"action_flag,omitempty"`
	ActionSource string `json:"action_source,omitempty"`
	ActionType   string `json:"action_type,omitempty"`
	CreateTime   string `json:"create_time,omitempty"`
	UserId       string `json:"user_id,omitempty"`
}
