/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// InlineObject32 struct for InlineObject32
type InlineObject32 struct {
	SupplierExtIds []string `json:"supplier_ext_ids,omitempty"`
}
