/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// InlineObject28 struct for InlineObject28
type InlineObject28 struct {
	CardId string `json:"card_id,omitempty"`
}
