/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// HotsearchSentencesRspDataList struct for HotsearchSentencesRspDataList
type HotsearchSentencesRspDataList struct {
	HotLevel int64  `json:"hot_level,omitempty"`
	Sentence string `json:"sentence,omitempty"`
}
