/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// InlineObject32 struct for InlineObject32
type InlineObject32 struct {
	// 订单支付状态。0 - 未支付, 1 - 已支付
	Status int64 `json:"status,omitempty"`
	// 抖音订单号
	OrderId string `json:"order_id,omitempty"`
	// 接入方商铺ID
	SupplierExtId string `json:"supplier_ext_id,omitempty"`
	// 接入方订单号
	OrderExtId string                            `json:"order_ext_id,omitempty"`
	DatePrice  []PoiExtHotelOrderCommitDatePrice `json:"date_price,omitempty"`
}
