/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// EnterpriseLeadsTagCreateReq
type EnterpriseLeadsTagCreateReq struct {
	TagName string `json:"tag_name,omitempty"`
}
