/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// PoiExtHotelOrderCommitRspData struct for PoiExtHotelOrderCommitRspData
type PoiExtHotelOrderCommitRspData struct {
	// 金额
	OrderExtId string `json:"order_ext_id,omitempty"`
	// 错误描述
	Description string `json:"description,omitempty"`
	// 返回错误码
	ErrorCode int64 `json:"error_code,omitempty"`
}
