/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// PoiExtHotelOrderCommitDatePrice struct for PoiExtHotelOrderCommitDatePrice
type PoiExtHotelOrderCommitDatePrice struct {
	// 入住日期 yyyyMMdd
	Date string `json:"date,omitempty"`
	// 入住日价格, 人民币分
	DatePrice int64 `json:"date_price,omitempty"`
}
