/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// InlineObject15 struct for InlineObject15
type InlineObject15 struct {
	// 客服id
	PersonaId string `json:"persona_id,omitempty"`
}
