/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// DataExternalPoiUserRspData struct for DataExternalPoiUserRspData
type DataExternalPoiUserRspData struct {
	// 错误描述
	Description string `json:"description,omitempty"`
	// 返回错误码
	ErrorCode  int64                                `json:"error_code,omitempty"`
	CityList   []DataExternalPoiUserRspDataCityList `json:"city_list,omitempty"`
	GenderList []DataExternalPoiUserRspDataCityList `json:"gender_list,omitempty"`
	AgeList    []DataExternalPoiUserRspDataCityList `json:"age_list,omitempty"`
}
