/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// InlineObject41 struct for InlineObject41
type InlineObject41 struct {
	// 素材id
	MediaId string `json:"media_id,omitempty"`
}
