/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// EnterpriseLeadsUserListRspDataUsers struct for EnterpriseLeadsUserListRspDataUsers
type EnterpriseLeadsUserListRspDataUsers struct {
	Age        string                                  `json:"age,omitempty"`
	Avatar     string                                  `json:"avatar,omitempty"`
	City       string                                  `json:"city,omitempty"`
	Gender     int32                                   `json:"gender,omitempty"`
	IsFollow   bool                                    `json:"is_follow,omitempty"`
	LeadsLevel int64                                   `json:"leads_level,omitempty"`
	Nickname   string                                  `json:"nickname,omitempty"`
	OpenId     string                                  `json:"open_id,omitempty"`
	Telephone  string                                  `json:"telephone,omitempty"`
	Wechat     string                                  `json:"wechat,omitempty"`
	TagList    []EnterpriseLeadsUserListRspDataTagList `json:"tag_list,omitempty"`
}
