/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// ConnectRspData struct for ConnectRspData
type ConnectRspData struct {
	Description string `json:"description,omitempty"`
	ErrorCode   int64  `json:"error_code,omitempty"`
}
