/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// PoiSpuSyncRsp
type PoiSpuSyncRsp struct {
	Data  PoiSpuSyncRspData `json:"data,omitempty"`
	Extra FansDataRspExtra  `json:"extra,omitempty"`
}
