/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// EnterpriseGrouponOrderOverviewRspDataRefunded struct for EnterpriseGrouponOrderOverviewRspDataRefunded
type EnterpriseGrouponOrderOverviewRspDataRefunded struct {
	Amount      int64                                                      `json:"amount,omitempty"`
	Count       int64                                                      `json:"count,omitempty"`
	SourceCount []EnterpriseGrouponOrderOverviewRspDataRefundedSourceCount `json:"source_count,omitempty"`
}
