/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// EnterpriseImMessageSendRsp
type EnterpriseImMessageSendRsp struct {
	Data  EnterpriseImMessageSendRspData `json:"data,omitempty"`
	Extra ConnectRspExtra                `json:"extra,omitempty"`
}
