/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// DataExternalUserItemRsp
type DataExternalUserItemRsp struct {
	Data  DataExternalUserItemRspData `json:"data,omitempty"`
	Extra FollowingListRspDataExtra   `json:"extra,omitempty"`
}
