/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// InlineObject22 struct for InlineObject22
type InlineObject22 struct {
	// 客服id
	PersonaId string `json:"persona_id,omitempty"`
	// 会话对方的open_id
	ToUserId string `json:"to_user_id,omitempty"`
}
