/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// EnterpriseMediaListRspData struct for EnterpriseMediaListRspData
type EnterpriseMediaListRspData struct {
	// 错误描述
	Description string `json:"description,omitempty"`
	// 返回错误码
	ErrorCode int64                              `json:"error_code,omitempty"`
	HasMore   bool                               `json:"has_more,omitempty"`
	Cursor    int64                              `json:"cursor,omitempty"`
	Medias    []EnterpriseMediaListRspDataMedias `json:"medias,omitempty"`
}
