/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// PoiSupplierSyncRspExtra struct for PoiSupplierSyncRspExtra
type PoiSupplierSyncRspExtra struct {
	// 标识请求的唯一id
	Logid string `json:"logid,omitempty"`
	// 毫秒级时间戳
	Now int64 `json:"now,omitempty"`
}
