/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// DataExternalPoiClaimListRspDataList struct for DataExternalPoiClaimListRspDataList
type DataExternalPoiClaimListRspDataList struct {
	// poi id
	PoiId string `json:"poi_id,omitempty"`
	// poi名称
	Name string `json:"name,omitempty"`
	// 地址详情
	Address string `json:"address,omitempty"`
}
