/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// PoiSupplierEntryEntryMiniApp 抖音小程序入口参数
type PoiSupplierEntryEntryMiniApp struct {
	// 服务路径
	Path string `json:"path,omitempty"`
	// 小程序的appid
	AppId string `json:"app_id,omitempty"`
	// 主要用于联调，1-使用测试版的小程序，0或者不填-使用正式版小程序
	IsTest int64 `json:"is_test,omitempty"`
	// 服务参数json
	Params string `json:"params,omitempty"`
}
