/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// InlineObject18 struct for InlineObject18
type InlineObject18 struct {
	// 标签id
	TagId int64 `json:"tag_id,omitempty"`
}
