/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// InlineObject26 struct for InlineObject26
type InlineObject26 struct {
	// 团购活动订单Id
	OrderId string `json:"order_id,omitempty"`
}
