/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// EnterpriseLeadsTagDeleteReq
type EnterpriseLeadsTagDeleteReq struct {
	// 标签id
	TagId int64 `json:"tag_id,omitempty"`
}
