/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// DiscoveryEntRankVersionRspDataList struct for DiscoveryEntRankVersionRspDataList
type DiscoveryEntRankVersionRspDataList struct {
	ActiveTime string `json:"active_time,omitempty"`
	EndTime    string `json:"end_time,omitempty"`
	StartTime  string `json:"start_time,omitempty"`
	Type       int32  `json:"type,omitempty"`
	Version    int32  `json:"version,omitempty"`
}
