/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// InlineObject33 struct for InlineObject33
type InlineObject33 struct {
	// 交易场景码，SEND_MONEY_REDPACKET 红包转账 SEND_VCOIN_REDPACKET 抖币转账
	TransCode string `json:"trans_code,omitempty"`
	// 数目
	Amount int64 `json:"amount,omitempty"`
	// 外部订单号，由调用方生成，长度小于64
	BizOrderNo string `json:"biz_order_no,omitempty"`
	// 业务id
	LiveId int64 `json:"live_id,omitempty"`
	// 商户id
	MerchantId int64 `json:"merchant_id,omitempty"`
	// 订单描述，长度小于256
	OrderDesc string `json:"order_desc,omitempty"`
	// 订单名称，长度小于64
	OrderName string `json:"order_name,omitempty"`
	// 标记，长度小于512
	Remark string `json:"remark,omitempty"`
}
