/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// DouyinVideoPositionSearchRspDataPois struct for DouyinVideoPositionSearchRspDataPois
type DouyinVideoPositionSearchRspDataPois struct {
	Address     string `json:"address,omitempty"`
	City        string `json:"city,omitempty"`
	CityCode    string `json:"city_code,omitempty"`
	Country     string `json:"country,omitempty"`
	CountryCode string `json:"country_code,omitempty"`
	District    string `json:"district,omitempty"`
	Location    string `json:"location,omitempty"`
	PoiId       string `json:"poi_id,omitempty"`
	PoiName     string `json:"poi_name,omitempty"`
	Province    string `json:"province,omitempty"`
}
