/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// PoiSkuSyncReqAttributes SKU属性字段
type PoiSkuSyncReqAttributes struct {
	// 酒店、名宿SKU日期
	Var1310 string `json:"1310,omitempty"`
}
