/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// InlineObject3 struct for InlineObject3
type InlineObject3 struct {
	ItemIds []string `json:"item_ids,omitempty"`
}
