/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// PoiOrderSyncRspData struct for PoiOrderSyncRspData
type PoiOrderSyncRspData struct {
	// 抖音平台订单ID
	OrderId string `json:"order_id,omitempty"`
	// 错误码描述
	ErrorCode int64 `json:"error_code,omitempty"`
	// 错误码描述
	Description string `json:"description,omitempty"`
}
