/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// PoiSupplierAttributes3101PreferentialPolicyExt 优待政策-扩展区(不超过1000个汉字)
type PoiSupplierAttributes3101PreferentialPolicyExt struct {
	// 节点内容
	Content string `json:"content,omitempty"`
	// 富文本处理中的节点类型 1 - text 2 - image
	NodeType int64 `json:"node_type,omitempty"`
}
