/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// EnterpriseLeadsTagUpdateReq
type EnterpriseLeadsTagUpdateReq struct {
	// 标签id
	TagId int64 `json:"tag_id,omitempty"`
	// 标签名称
	TagName string `json:"tag_name,omitempty"`
}
