/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// EnterpriseGrouponOrderDetailRspDataOrderInfo struct for EnterpriseGrouponOrderDetailRspDataOrderInfo
type EnterpriseGrouponOrderDetailRspDataOrderInfo struct {
	Amount         int64                                      `json:"amount,omitempty"`
	BuyerOpenId    string                                     `json:"buyer_open_id,omitempty"`
	Channel        string                                     `json:"channel,omitempty"`
	CreateTime     int64                                      `json:"create_time,omitempty"`
	ItemCount      int64                                      `json:"item_count,omitempty"`
	OrderId        string                                     `json:"order_id,omitempty"`
	OriginalAmount int64                                      `json:"original_amount,omitempty"`
	PayTime        int64                                      `json:"pay_time,omitempty"`
	RefundAmount   int64                                      `json:"refund_amount,omitempty"`
	RefundTime     int64                                      `json:"refund_time,omitempty"`
	SettleAmount   int64                                      `json:"settle_amount,omitempty"`
	Status         string                                     `json:"status,omitempty"`
	Codes          []EnterpriseGrouponOrderDetailRspDataCodes `json:"codes,omitempty"`
}
