/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// EnterpriseGrouponOrderDetailRspDataCodes struct for EnterpriseGrouponOrderDetailRspDataCodes
type EnterpriseGrouponOrderDetailRspDataCodes struct {
	Code        string `json:"code,omitempty"`
	ConfirmTime int64  `json:"confirm_time,omitempty"`
	EndTime     int64  `json:"end_time,omitempty"`
	GrouponId   string `json:"groupon_id,omitempty"`
	StartTime   int64  `json:"start_time,omitempty"`
	Status      string `json:"status,omitempty"`
}
