/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// VideoCommentTopReq
type VideoCommentTopReq struct {
	// true置顶, false取消置顶
	Top bool `json:"top,omitempty"`
	// 需要回复的评论id
	CommentId string `json:"comment_id,omitempty"`
	// 视频id
	ItemId string `json:"item_id,omitempty"`
}
