/*
 * 抖音开放API
 *
 * douyin open api
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package douyin

// PoiSkuSyncReq
type PoiSkuSyncReq struct {
	// 外部平台SPU ID
	SpuExtId string              `json:"spu_ext_id,omitempty"`
	Skus     []PoiSkuSyncReqSkus `json:"skus,omitempty"`
}
